version: 2.1

orbs: 
  aws-ecr: circleci/aws-ecr@8.1.2

jobs:
  arm-build:
    machine:
      image: ubuntu-2004:current
    resource_class: arm.medium
    steps:
      - checkout
      - aws-ecr/build-and-push-image:
          repo: "${AWS_RESOURCE_NAME_PREFIX}"
          region: ${AWS_DEFAULT_REGION}
          tag: "arm-${CIRCLE_SHA1}"

  x86-build:
    machine:
      image: ubuntu-2004:current
    resource_class: x86.medium
    steps:
      - checkout
      - aws-ecr/build-and-push-image:
          repo: "${AWS_RESOURCE_NAME_PREFIX}"
          region: ${AWS_DEFAULT_REGION}
          tag: "x86-${CIRCLE_SHA1}"

workflows:
  version: 2
  deploy:
    jobs:
      - arm-build
      - x86-build