version: 2.1

orbs: 
  aws-ecr: circleci/aws-ecr@8.1.2

jobs:
  arm-build:
    machine:
      image: ubuntu-2004:current
    resource_class: arm.medium
    steps:
      - checkout
      - aws-ecr/build-and-push-image:
          repo: "${AWS_RESOURCE_NAME_PREFIX}"
          region: ${AWS_DEFAULT_REGION}
          tag: "${CIRCLE_BUILD_NUM}-${CIRCLE_SHA1}"
          platform: linux/arm64
    manifests:
      description: "Make and Push Manifests for Docker"
      steps:
        - checkout
        - run:
            name: Make Manifests
            command: |
              ./.ci/manifest.sh --image ${DOCKER_IMAGE} --manifest ${VERSION}-${CIRCLE_SHA1} --push
              ./.ci/manifest.sh --image ${DOCKER_IMAGE} --manifest ${CIRCLE_SHA1} --push
              ./.ci/manifest.sh --image ${DOCKER_IMAGE} --manifest ${VERSION} --push
              ./.ci/manifest.sh --image ${DOCKER_IMAGE} --manifest latest --push          

  x86-build:
    machine:
      image: ubuntu-2004:current
    resource_class: medium
    steps:
      - checkout
      - aws-ecr/build-and-push-image:
          repo: "${AWS_RESOURCE_NAME_PREFIX}"
          region: ${AWS_DEFAULT_REGION}
          tag: "${CIRCLE_BUILD_NUM}-${CIRCLE_SHA1}"
          platform: linux/amd64

workflows:
  version: 2
  multiarch-deploy:
    jobs:
      - arm-build
      - x86-build
