version: 2.1

orbs: 
  aws-ecr: circleci/aws-ecr@8.1.2

jobs:
  arm-build:
    machine:
      image: ubuntu-2004:current
    resource_class: arm.medium
    steps:
      - checkout
      - aws-ecr/build-and-push-image:
          repo: "${AWS_RESOURCE_NAME_PREFIX}"
          region: ${AWS_DEFAULT_REGION}
          tag: "arm"
          platform: linux/arm64

  x86-build:
    machine:
      image: ubuntu-2004:current
    resource_class: medium
    steps:
      - checkout
      - aws-ecr/build-and-push-image:
          repo: "${AWS_RESOURCE_NAME_PREFIX}"
          region: ${AWS_DEFAULT_REGION}
          tag: "x86"
          platform: linux/amd64

workflows:
  version: 2
  multiarch-deploy:
    jobs:
      - arm-build
      - x86-build
